name: Generate Documentation by JSDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Setup git
        run: |
          git config --global user.name 'ebot'
          git config --global user.email 'ebot@elmenov.com'
          git checkout -b gh-pages
      - name: Generate docs
        run: npx typedoc
      - name: Commit docs
        run: |
          git add .
          git commit -a "Update documentation"
          git push origin gh-pages
