name: Generate Documentation by JSDoc

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Setup git
        run: |
          git config --global user.name 'ebot'
          git config --global user.email 'ebot@elmenov.com'
          git checkout -b docs/${{ github.run_id }}
      - name: Generate documentation
        run: npx typedoc
      - name: Commit documentation
        run: |
          git add .
          git commit -am "Autocommit with generated documentation"
          git push --set-upstream origin docs/${{ github.run_id }}
      - name: Create PR
        run: gh pr create --fill --head=docs/${{ github.run_id }} --title 'Merge docs/${{ github.run_id }} into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
